/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class appenv_jni_APIStub */

#ifndef _Included_appenv_jni_APIStub
#define _Included_appenv_jni_APIStub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     appenv_jni_APIStub
 * Method:    testNativeCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_appenv_jni_APIStub_testNativeCall
  (JNIEnv *, jclass);

/*
 * Class:     appenv_jni_APIStub
 * Method:    lfence
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_appenv_jni_APIStub_lfence
  (JNIEnv *, jclass);

/*
 * Class:     appenv_jni_APIStub
 * Method:    sfence
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_appenv_jni_APIStub_sfence
  (JNIEnv *, jclass);

/*
 * Class:     appenv_jni_APIStub
 * Method:    sync_lock_test_and_set
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_appenv_jni_APIStub_sync_1lock_1test_1and_1set
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     appenv_jni_APIStub
 * Method:    sync_val_compare_and_swap
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_appenv_jni_APIStub_sync_1val_1compare_1and_1swap
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     appenv_jni_APIStub
 * Method:    sync_lock_release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_appenv_jni_APIStub_sync_1lock_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     appenv_jni_APIStub
 * Method:    lock_cas
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_appenv_jni_APIStub_lock_1cas
  (JNIEnv *, jclass, jlong);

/*
 * Class:     appenv_jni_APIStub
 * Method:    lock_tas
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_appenv_jni_APIStub_lock_1tas
  (JNIEnv *, jclass, jlong);

/*
 * Class:     appenv_jni_APIStub
 * Method:    unlock_sfence
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_appenv_jni_APIStub_unlock_1sfence
  (JNIEnv *, jclass, jlong);

/*
 * Class:     appenv_jni_APIStub
 * Method:    unlock_dummy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_appenv_jni_APIStub_unlock_1dummy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     appenv_jni_APIStub
 * Method:    unlock_lock_release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_appenv_jni_APIStub_unlock_1lock_1release
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
